import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Writes the ExitRouter ABI from the Foundry artifact into a typed TypeScript module, so the relayer, the
// routes and the tests share one source of truth. Run after `forge build`.

const artifactPath = resolve("out/ExitRouter.sol/ExitRouter.json");
const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown[]; deployedBytecode?: { object?: string } };
if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) throw new Error("ExitRouter ABI is empty; run forge build first");

const outPath = resolve("src/exit-router-abi.ts");
const body = `// Generated by scripts/export-exit-router-abi.ts from out/ExitRouter.sol/ExitRouter.json. Do not edit by hand.

export const exitRouterAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
writeFileSync(outPath, body);
console.log(`wrote ${outPath} (${artifact.abi.length} ABI entries)`);
