import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Writes the ABIs of the gift contracts from their Foundry artifacts into typed TypeScript modules, so the relayer,
// the routes and the tests share one source of truth. Run after `forge build`. Every contract that holds a gift
// keeps its ABI here: the first version's two, the second version's two, and the third daily contract.

const contracts = [
  { name: "GiftEscrow", constant: "giftEscrowAbi", out: "src/gift-escrow-abi.ts" },
  { name: "MilestoneGift", constant: "milestoneGiftAbi", out: "src/milestone-gift-abi.ts" },
  { name: "GiftEscrowV2", constant: "giftEscrowV2Abi", out: "src/gift-escrow-v2-abi.ts" },
  { name: "MilestoneGiftV2", constant: "milestoneGiftV2Abi", out: "src/milestone-gift-v2-abi.ts" },
  { name: "GiftEscrowV3", constant: "giftEscrowV3Abi", out: "src/gift-escrow-v3-abi.ts" },
  { name: "ConsentAnchor", constant: "consentAnchorAbi", out: "src/consent-anchor-abi.ts" },
] as const;

for (const contract of contracts) {
  const artifactPath = resolve(`out/${contract.name}.sol/${contract.name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown[] };
  if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) throw new Error(`${contract.name} ABI is empty; run forge build first`);
  const outPath = resolve(contract.out);
  const body = `// Generated by scripts/export-gift-abi.ts from out/${contract.name}.sol/${contract.name}.json. Do not edit by hand.

export const ${contract.constant} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  writeFileSync(outPath, body);
  console.log(`wrote ${outPath} (${artifact.abi.length} ABI entries)`);
}
