import { createPublicClient, createWalletClient, erc20Abi, getAddress, http, type Abi, type Hex, type PublicClient, type WalletClient } from "viem";
import { privateKeyToAccount, type PrivateKeyAccount } from "viem/accounts";
import { base } from "viem/chains";
import { transferAuthorizationMessage, transferAuthorizationTypedData } from "./ausd-authorization";
import { AUSD } from "./coins";
import { AUSD_ADDRESS, monadChain, waitForFinality } from "./monad/chain";
import { addMonadGasBuffer } from "./monad-gas";
import { relayerClients, relayerPreflight, type RelayerClients } from "./relayer";

/**
 * Viky's treasury for the phone way out (D238): one key, one address, on two chains. On Monad it receives the person's
 * AUSD and, when Bitrefill fails after that, sends it back; on Base it pays Bitrefill's invoice in USDC, since Bitrefill
 * does not take Monad. It is distinct from the relayer, and generated by the founder (docs/OPERATIONS.md).
 *
 * On Monad the treasury makes no call of its own: an account below the 10 MON reserve can make none (D53), so a refund
 * is an AUSD authorization the treasury signs and the relayer carries, as a person's own send is. On Base it pays its
 * own fee in ETH, which the founder funds with the USDC.
 */

/** Circle's USDC on Base mainnet (developers.circle.com, "USDC contract addresses", read 25 Sep 2026). */
export const BASE_USDC_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" as const;

export type TreasuryErrorCode = "NOT_CONFIGURED" | "TREASURY_SHORT" | "PAYMENT_FAILED" | "PAYMENT_UNCONFIRMED" | "REFUND_FAILED";

export class TreasuryError extends Error {
  constructor(
    readonly code: TreasuryErrorCode,
    message: string,
    options?: { cause?: unknown; hash?: Hex },
  ) {
    super(message, options);
    this.name = "TreasuryError";
    this.hash = options?.hash;
  }

  /** The payment's hash when it was sent and its fate is not known yet (`PAYMENT_UNCONFIRMED`). */
  readonly hash?: Hex;
}

/**
 * The treasury's account, from its key, checked against the address the founder shared: a key that does not make that
 * address is refused rather than used, so a variable pasted in the wrong place moves nothing.
 */
export function treasuryAccount(env: NodeJS.ProcessEnv = process.env): PrivateKeyAccount {
  const key = env.TREASURY_PRIVATE_KEY?.trim();
  const shared = env.TREASURY_ADDRESS?.trim();
  if (!key || !shared) throw new TreasuryError("NOT_CONFIGURED", "The treasury is not configured");
  let account: PrivateKeyAccount;
  try {
    account = privateKeyToAccount((key.startsWith("0x") ? key : `0x${key}`) as Hex);
  } catch (error) {
    throw new TreasuryError("NOT_CONFIGURED", "The treasury's key is not a key", { cause: error });
  }
  if (getAddress(account.address) !== getAddress(shared)) throw new TreasuryError("NOT_CONFIGURED", "The treasury's key does not make the address that was shared");
  if (env.RELAYER_PRIVATE_KEY?.trim() && privateKeyToAccount((env.RELAYER_PRIVATE_KEY.trim().startsWith("0x") ? env.RELAYER_PRIVATE_KEY.trim() : `0x${env.RELAYER_PRIVATE_KEY.trim()}`) as Hex).address === account.address) {
    throw new TreasuryError("NOT_CONFIGURED", "The treasury must not be the relayer");
  }
  return account;
}

/** Where the person's AUSD goes, without the key: the address alone is enough to price and to check. */
export function treasuryAddress(env: NodeJS.ProcessEnv = process.env): Hex {
  const shared = env.TREASURY_ADDRESS?.trim();
  if (!shared || !/^0x[0-9a-fA-F]{40}$/.test(shared)) throw new TreasuryError("NOT_CONFIGURED", "The treasury is not configured");
  return getAddress(shared);
}

export function treasuryConfigured(env: NodeJS.ProcessEnv = process.env): boolean {
  try {
    treasuryAccount(env);
    return true;
  } catch {
    return false;
  }
}

export type BaseClients = Readonly<{ publicClient: PublicClient; walletClient: WalletClient; account: PrivateKeyAccount }>;

/** Base, through `BASE_RPC_URL` when set and Base's own public endpoint otherwise. */
export function baseClients(env: NodeJS.ProcessEnv = process.env): BaseClients {
  const account = treasuryAccount(env);
  const transport = http(env.BASE_RPC_URL?.trim() || "https://mainnet.base.org");
  return {
    publicClient: createPublicClient({ chain: base, transport }) as PublicClient,
    walletClient: createWalletClient({ chain: base, transport, account }),
    account,
  };
}

/** What the treasury holds where it pays: USDC and ETH on Base, in their own units. */
export async function treasuryOnBase(clients: BaseClients = baseClients()): Promise<{ usdcUnits: bigint; ethWei: bigint }> {
  const [usdcUnits, ethWei] = await Promise.all([
    clients.publicClient.readContract({ address: BASE_USDC_ADDRESS, abi: erc20Abi, functionName: "balanceOf", args: [clients.account.address] }) as Promise<bigint>,
    clients.publicClient.getBalance({ address: clients.account.address }),
  ]);
  return { usdcUnits, ethWei };
}

/** Whether the treasury can pay this invoice now: checked before the person is asked for anything. */
export async function treasuryCovers(usdcUnits: bigint, clients: BaseClients = baseClients()): Promise<boolean> {
  const held = await treasuryOnBase(clients);
  return held.usdcUnits >= usdcUnits && held.ethWei > 0n;
}

/** Pays one invoice: the exact USDC Bitrefill asked, to the address it gave, on Base, and waits for the receipt. */
export async function payInvoiceOnBase(input: Readonly<{ to: string; usdcUnits: bigint }>, clients: BaseClients = baseClients()): Promise<{ hash: Hex }> {
  if (!/^0x[0-9a-fA-F]{40}$/.test(input.to)) throw new TreasuryError("PAYMENT_FAILED", "Bitrefill's payment address is not an address on Base");
  if (input.usdcUnits <= 0n) throw new TreasuryError("PAYMENT_FAILED", "Nothing to pay");
  if (!(await treasuryCovers(input.usdcUnits, clients))) throw new TreasuryError("TREASURY_SHORT", "The treasury cannot pay this right now");
  let hash: Hex;
  try {
    hash = await clients.walletClient.writeContract({ address: BASE_USDC_ADDRESS, abi: erc20Abi, functionName: "transfer", args: [getAddress(input.to), input.usdcUnits], account: clients.account, chain: base });
  } catch (error) {
    throw new TreasuryError("PAYMENT_FAILED", "The treasury's payment was not sent", { cause: error });
  }
  let receipt;
  try {
    receipt = await clients.publicClient.waitForTransactionReceipt({ hash, confirmations: 2 });
  } catch (error) {
    // Sent, and not known yet: it may still land, so it is followed and never refunded as if it had failed.
    throw new TreasuryError("PAYMENT_UNCONFIRMED", "The treasury's payment is not confirmed yet", { cause: error, hash });
  }
  if (receipt.status !== "success") throw new TreasuryError("PAYMENT_FAILED", "The treasury's payment failed on Base");
  return { hash };
}

const TRANSFER_WITH_AUTHORIZATION_ABI = [
  {
    type: "function",
    name: "transferWithAuthorization",
    stateMutability: "nonpayable",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
      { name: "validAfter", type: "uint256" },
      { name: "validBefore", type: "uint256" },
      { name: "nonce", type: "bytes32" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
] as const satisfies Abi;

/**
 * Sends a person's AUSD back from the treasury: the treasury signs the transfer, the relayer carries it and pays the
 * fee. The nonce is the order's own, so one order can be refunded once and never twice, whatever retries.
 */
export async function refundAusd(
  input: Readonly<{ to: Hex; ausdUnits: bigint; nonce: Hex }>,
  deps: Readonly<{ account?: PrivateKeyAccount; relayer?: RelayerClients }> = {},
): Promise<{ hash: Hex }> {
  const account = deps.account ?? treasuryAccount();
  const relayer = deps.relayer ?? relayerClients();
  const message = transferAuthorizationMessage({ from: account.address, to: getAddress(input.to), value: input.ausdUnits, nonce: input.nonce });
  const signature = await account.signTypedData(transferAuthorizationTypedData(message, AUSD));
  const args = [message.from, message.to, message.value, message.validAfter, message.validBefore, message.nonce, signature] as const;
  try {
    await relayerPreflight(relayer);
    await relayer.publicClient.simulateContract({ address: AUSD_ADDRESS, abi: TRANSFER_WITH_AUTHORIZATION_ABI, functionName: "transferWithAuthorization", args, account: relayer.address });
    const estimate = await relayer.publicClient.estimateContractGas({ address: AUSD_ADDRESS, abi: TRANSFER_WITH_AUTHORIZATION_ABI, functionName: "transferWithAuthorization", args, account: relayer.address });
    const hash = await relayer.walletClient.writeContract({ address: AUSD_ADDRESS, abi: TRANSFER_WITH_AUTHORIZATION_ABI, functionName: "transferWithAuthorization", args, gas: addMonadGasBuffer(estimate), account: relayer.walletClient.account!, chain: monadChain });
    const receipt = await waitForFinality(relayer.publicClient, hash);
    if (receipt.status !== "success") throw new Error("reverted");
    return { hash };
  } catch (error) {
    throw new TreasuryError("REFUND_FAILED", "The refund could not be sent yet", { cause: error });
  }
}
